on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: deploy DB
        run: |
          sudo apt update
          sudo apt -y install postgresql-client
          PGPASSWORD=${{ secrets.PGPASS }} psql -U ${{ secrets.PGUSER }} -h ${{ secrets.PGCONNECTIONSTRING }} -d ${{ secrets.PG }} -i createTables.sql
