
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: deploy DB
        run: |
          sudo apt update
          sudo apt -y install postgresql-client
          PGPASSWORD=${(PGPASS)} psql -U ${(PGUSER)} -h ${(PGCONNECTIONSTRING)} -d ${(PG)} -f createTables.sql
