on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: deploy DB
        run: |
          sudo apt update
          sudo apt -y install postgresql-client
          PGPASSWORD=${{ secrets.PGPASS }} psql -U ${{ secrets.PGUSER }} -h database-1.cxk0mccsmcso.us-east-1.rds.amazonaws.com:5432 -d ${{ secrets.PGDBNAME }} -f createTables.sql
